loglevel: info
SshFileSystemDefaultOpenPath: /root/pipelines

SshConnectionInfo:
  hostAddr: 172.25.48.190
  port: 22
  username: root
  password: unknown 
  publicKey: C:/Users/19269/.ssh/id_rsa.pub 
  privateKey: C:/Users/19269/.ssh/id_rsa 